// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFuncioanrioMVC.Data;

#nullable disable

namespace SistemaFuncioanrioMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106131049_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaFuncioanrioMVC.Models.Funcionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salarioBase")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("TabelaFuncionario");

                    b.HasDiscriminator<string>("cargo").HasValue("Funcionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaFuncioanrioMVC.Models.Gerente", b =>
                {
                    b.HasBaseType("SistemaFuncioanrioMVC.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Gerente");
                });

            modelBuilder.Entity("SistemaFuncioanrioMVC.Models.Vendedor", b =>
                {
                    b.HasBaseType("SistemaFuncioanrioMVC.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
