// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaVeiculosMVC.Data;

#nullable disable

namespace SistemaVeiculosMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110134552_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaVeiculosMVC.Models.Veiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ano")
                        .HasColumnType("int");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("veiculo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("id");

                    b.ToTable("TabelaVeiculo");

                    b.HasDiscriminator<string>("veiculo").HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaVeiculosMVC.Models.Carro", b =>
                {
                    b.HasBaseType("SistemaVeiculosMVC.Models.Veiculo");

                    b.HasDiscriminator().HasValue("Carro");
                });

            modelBuilder.Entity("SistemaVeiculosMVC.Models.Moto", b =>
                {
                    b.HasBaseType("SistemaVeiculosMVC.Models.Veiculo");

                    b.HasDiscriminator().HasValue("Moto");
                });
#pragma warning restore 612, 618
        }
    }
}
